### ISSUE TITLE
SSH Inception TODO

### ISSUE THREAD

**Issue by newjam** [edurange/edurange-server#73]
_These were copied from from [a file](https://github.com/edurange/edurange-server/blob/b70d9790ce151acc2476d9941139dc6afd13a0b0/ssh_inception_notes.md) before deleting it._
* [ ] Add level where students create a key pair and add their key to a server
* [ ] Move Starting Line to a new subnet that is publically accessible so that students don't have to log into the NAT first.
* [ ] Fix chef script problems on NAT
